### ISSUE TITLE
DeprecationWarning on escape sequence in setup.py

### ISSUE THREAD

**Issue by nhjjreuter** [psyinfra/HTCrystalBall#42]
```
  /home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/htcondor-8.9.9a1-py3.6-linux-x86_64.egg/htcondor/__init__.py:58: DeprecationWarning: invalid escape sequence \d

    __version__ = _re.match("^.*(\d+\.\d+\.\d+)", htcondor.version()).group(1)
```

The regex used here grabs the version from the version string, but it seems that `\d` is deprecated.

**Comment by aqw** [comment]
This is actually a warning in the htcondor package, not htcrystalball, so we're ok here.

Though as an explanation of the issue (as this deprecation warning is new to me):
The issue here is that `\` is meant for string literals (like `\n` for newline), hence the change in behavior. We need to either escape the `\` (as in `\\d`) or use raw strings, which I think is a more readable solution here, given the already high cognitive load for mentally parsing regex strings.

I grep-ed through the code, and all instances of regex I could find do the right thing (raw strings). So I think we can safely close this issue.
